version: "3.7"
services:
    mqtt:
        image: eclipse-mosquitto
        ports:
            - 1883
        container_name: mqtt_container

    mongodb:
        image: mongo
        ports:
            - 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: germany
            MONGO_INITDB_ROOT_PASSWORD: germany
            MONGO_INITDB_DATABASE: primedb
        links:
            - app
        container_name: mongodb_container

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 85:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: germany
            ME_CONFIG_MONGODB_ADMINPASSWORD: germany
            ME_CONFIG_MONGODB_SERVER: mongodb_container
        container_name: mongo_express_container

    app:
        build: .
        depends_on:
            - mqtt
        container_name: app_container
        
            #networks:
        #default:
        #external:
        #    name: timber
